# This file specifies which linters golangci-lint should run.
#
# For descriptions of all available linters, run:
# ./.golangci-lint-1.17.1 linters
# or browse to:
# https://github.com/golangci/golangci-lint#supported-linters

run:
  deadline: 5m
  skip-dirs:
  - controller/gen
issues:
  exclude-use-default: false
  exclude-rules:
  # Append should be able to assign to a different var/slice.
  - linters:
    - gocritic
    text: "appendAssign: append result not assigned to the same slice"
  - linters:
    - gocritic
    text: "singleCaseSwitch: should rewrite switch statement to if statement"
  - linters:
    - gocritic
    text: "ifElseChain: rewrite if-else to switch statement"

linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - errcheck
  - errorlint
  - exportloopref
  - goconst
  - gocritic
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - revive
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  # TODO: enable more linters!
  # - dupl
  # - gochecknoglobals
  # - gochecknoinits
  # - gocyclo
  # - interfacer
  # - lll
  # - maligned
  # - prealloc
  # - stylecheck
  disable:
  - staticcheck
  - structcheck

issues:
  exclude-rules:
    # Linters
    #########
    - linters:
      - errcheck
      text: Error return value of `((io|out|w)\.(Copy|Write))` is not checked
    # MarkHidden is fallible if the flag does not exist. We assume these exist
    # exist as they are generally flags we are deprecating or use only for
    # development.
    - linters:
      - errcheck
      text: Error return value of `.*\.MarkHidden` is not checked
    # Flag completion is not critical to the CLI and errors are ignored if
    # registration fails.
    - linters:
      - errcheck
      text: Error return value of `.*\.RegisterFlagCompletionFunc` is not checked
    # Errors that occur when gracefully shutting down control plane components
    # are insignificant.
    - linters:
      - errcheck
      text: Error return value of `(adminServer|server)\.Shutdown` is not checked

    # Paths
    #######
    # We make assumptions about the number of events we expect to process, and
    # if processNextEvent fails that will still surface in the test.
    - path: _test.*\.go
      text: Error return value of `watcher.processNextEvent` is not checked
